// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxlqohzdzpquovptnrge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4bHFvaHpkenBxdW92cHRucmdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NzA5MzQsImV4cCI6MjA3MDQ0NjkzNH0.Gxnv_0kycckuD8wY0PC2I879lMJWdpMBk3SS62t305w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});